### ISSUE TITLE
6.2.0(3968)bilibili服扫码成功不能自动登录

### ISSUE THREAD

**Issue by 230Chen** [HonkaiScanner/bh3_login_simulation#24]
![Screenshot_2022-11-10-10-51-44-781_com.github.haocen2004.bh3_login_simulation.jpg](https://user-images.githubusercontent.com/82554411/200989264-808615e8-a582-4ba3-bbff-861f430b4072.jpg)

**Comment by Haocen2004** [comment]
请提供日志

**Comment by 230Chen** [comment]
一小时前会提示按键确认登录，刚刚测试登录一遍又能登陆了，抱歉打扰
