### ISSUE TITLE
[Bug] 华为服无法正常登录

### ISSUE THREAD

**Issue by ydxdxax** [HonkaiScanner/bh3_login_simulation#32]
**用一句话描述一下bug**
在我试图给应用授权的时候，应用闪退了，连试几次都没用

**如何触发这个bug**
Bug触发的步骤:
1. 打开应用
2.  授权华为账号
3. 闪退
4. 

**预期行为**
如果没有bug，应该会跳出授权界面，授权后应用会显示已登录

**截图**
![Screenshot_20221228_163654](https://user-images.githubusercontent.com/121544258/209783609-9671e270-19f1-4018-a5b1-a95b222ab181.jpg)

**设备信息:**
 - 设备: Vivo Y85A
 - 系统版本: Android 8.0
 - 应用版本 1.7.2

**额外内容**
[{level='长按', TAG='复制日志', message='长按该条复制所有'}, {level='INFO', TAG='dialogHelper', message='loading...'}, {level='INFO', TAG='dialogHelper', message='eula checked, skip.'}, {level='INFO', TAG='Update', message='handleMessage: {"ver":50,"ver_name":"1.7.2","bh_ver":"6.3.0","update_url":"https://haocen.lanzoum.com/b01ovffcj","default_name":"崩坏3扫码器用户","logs":"## 1.7.2\n修复了几个导致扫码器崩溃的bug\n1.7.1可能打不开更新链接\n优先前往酷安或群内更新\n\n## 1.7.1\n- 修复 vivo登陆闪退\n## 1.7.0\n- 增加 华为服\n- 增加 应用宝-qq\n- 积累bug修复\n更多更新日志可前往github查看\n\n提取码193x","sp_url":"https://scanner.hellocraft.xyz","mdk_ver":"1.25.1","afd_url":"https://afdian.net/@Haocen2004","qq_group_url":"https://jq.qq.com/?_wv=1027&k=NpL8j6r7","update_time":1668049200}'}]

**Comment by Haocen2004** [comment]
出现崩溃界面时额外内容应为此界面导出的崩溃报告
软件崩溃重启不会保留日志

**Comment by Haocen2004** [comment]
长时间无后续反馈 暂时关闭
